name: SPT-Server Build Master

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    paths:
      - '.github/workflows/build-master.yml'

env:
  SERVER_SRC_URL: https://raw.githubusercontent.com/sp-tarkov/server
  BRANCH: master

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      SPT_VERSION: ${{ steps.versions.outputs.SPT_VERSION }}

    steps:
      - name: Extract version
        id: versions
        run: |
          wget  ${{ env.SERVER_SRC_URL }}/refs/heads/${{ env.BRANCH }}/project/assets/configs/core.json

          SPT_VERSION=$(jq -r '.sptVersion' core.json)

          echo "👽 SPT_VERSION = $SPT_VERSION"
          echo "SPT_VERSION=$SPT_VERSION" >> $GITHUB_OUTPUT

  build-server:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64
          tags: |
            irorikon/spt-server:latest
            irorikon/spt-server:master
            irorikon/spt-server:${{needs.prepare.outputs.SPT_VERSION}}
          push: true